version: '3.0'
services:
  postgresql:
    image: 'postgres:13'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro'
  mongodb:
    image: 'mongo:5.0.3'
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ''
      ME_CONFIG_BASICAUTH_PASSWORD: ''
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
