spring:
  flyway:
    batch:
      schemas: public
      locations: 'classpath:db/migration/batch'
      create-schemas: false
      clean-at-start: true
      clean-disabled: false
      migrate-at-start: true
      baseline-on-migrate: true
    stg:
      schemas: stg
      locations: 'classpath:db/migration/stg'
      create-schemas: false
      clean-at-start: true
      clean-disabled: false
      migrate-at-start: true
      baseline-on-migrate: true
    #dwh:
    #  schemas: dwh
    #  locations: 'classpath:db/migration/dwh'
    #  create-schemas: false
    #  clean-at-start: true
    #  clean-disabled: false
    #  migrate-at-start: true
    #  baseline-on-migrate: true
    #dm_companies:
    #  schemas: dm_companies
    #  locations: 'classpath:db/migration/dm_companies'
    #  create-schemas: false
    #  clean-at-start: true
    #  clean-disabled: false
    #  migrate-at-start: true
    #  baseline-on-migrate: true
  log:
    category:
      'fr.dademo.bi':
        level: DEBUG
      'fr.dademo.bi.companies.tools':
        level: TRACE
        min-level: TRACE
      'org.flywaydb.core':
        level: DEBUG
      'org.jooq.Constants':
        level: WARNING
      'okhttp3':
        level: DEBUG

datasource:
  jdbc:
    stg:
      url: jdbc:postgresql://localhost:5432/bi
      username: bi_rw
      password: bi_rw
  mongodb:
    enabled: false
    connection-string: mongodb://localhost:27017/stg

jobs:
  naf:
    enabled: true
    batch-size: 1000
    writer-type: JDBC
  company:
    enabled: false
    batch-size: 100000
    writer-type: NO_ACTION
  company-history:
    enabled: false
    batch-size: 100000
    writer-type: NO_ACTION
  company-inheritance:
    enabled: false
    batch-size: 100000
    writer-type: NO_ACTION
  company-legal:
    enabled: false
    batch-size: 100000
    writer-type: NO_ACTION
  company-legal-history:
    enabled: false
    batch-size: 100000
    writer-type: NO_ACTION
  association:
    enabled: true
    batch-size: 100000
    writer-type: NO_ACTION
  association-waldec:
    enabled: true
    batch-size: 100000
    writer-type: NO_ACTION
