quarkus:
  arc:
    unremovable-types: com.fasterxml.jackson.databind.ObjectMapper
  datasource:
    db-kind: postgresql
    username: bi
    password: bi
    jdbc:
      url: jdbc:postgresql://localhost:5432/bi
      max-size: 16
  hibernate-orm:
    database:
      generation: none
    jdbc:
      statement-batch-size: 10000
  flyway:
    schemas: 'public,dwh,dm_companies'
    locations: 'db/migration'
    create-schemas: true
    clean-at-start: true
    migrate-at-start: true
  log:
    category:
      'fr.dademo.bi':
        level: DEBUG
      'org.flywaydb.core':
        level: DEBUG
      'okhttp3':
        level: DEBUG
      'camel_jobs':
        level: DEBUG

camel:
  # You can use a hard FS instead of memory if processing consume too much
  spool-directory: "${java.io.tmpdir}/camel/camel-tmp-#uuid#"
  jobs:
    naf:
      enabled: true
    companies-history:
      enabled: true
      batch-size: 100000
