spring:
  batch:
    initialize-schema: always

flyway:
  apply-migrations: true
  migrations:
    batch:
      enabled: true
      schemas: public
    stg:
      enabled: true
      schemas: stg

amqp:
  createQueues: true
  createExchanges: true

logging:
  level:
    #'org.springframework': DEBUG
    'org.springframework': INFO
    'fr.dademo': DEBUG
    'fr.dademo.tools': TRACE
    'org.flywaydb.core': DEBUG
    'org.jooq.Constants': WARN
    #'com.zaxxer.hikari': DEBUG
    'com.zaxxer.hikari': INFO
    #'okhttp3': DEBUG
    'okhttp3': INFO

cache:
  enabled: true

datasources:
  jdbc:
    batch:
      enabled: true
      #driver-class-name: org.sqlite.JDBC
      #url: "jdbc:sqlite:jobs.sqlite"
      url: jdbc:postgresql://localhost:5432/bi
      minimum-idle: 5
      maximum-pool-size: 10
      username: bi_rw
      password: bi_rw
    stg:
      enabled: true
      url: jdbc:postgresql://localhost:5432/bi
      minimum-idle: 5
      maximum-pool-size: 100
      username: bi_rw
      password: bi_rw
  mongodb:
    batch-repository:
      connection-string: mongodb://root:root@localhost:27017/batch
      database: batch
    stg:
      enabled: true
      connection-string: mongodb://root:root@localhost:27017/stg
      database: stg
  rabbitmq:
    stg:
      enabled: true
      connection-string: amqp://guest:guest@localhost:5672
      confirms: false
      queues: { }
      exchanges:
        association:
          name: association
          type: direct
          durable: true
          autoDelete: false
          delayed: false
          internal: false

batch:
  repository:
    enabled: true
    table-prefix: BATCH_
  jobs:
    naf:
      enabled: true
      chunk-size: 1000
      writer-type: NO_ACTION
      #writer-type: MONGODB
      max-threads: null
    company:
      enabled: false
      chunk-size: 100000
      writer-type: NO_ACTION
      #writer-type: MONGODB
      max-threads: null
    company-history:
      enabled: false
      chunk-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    company-inheritance:
      enabled: false
      chunk-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    company-legal:
      enabled: false
      chunk-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    company-legal-history:
      enabled: false
      chunk-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    association:
      enabled: false
      chunk-size: 100000
      writer-type: AMQP
      max-threads: null
    association-waldec:
      enabled: false
      chunk-size: 100000
      writer-type: NO_ACTION
      max-threads: null
