spring:
  flyway:
    batch:
      schemas: public
      locations: 'classpath:db/migration/batch'
      create-schemas: false
      clean-at-start: true
      clean-disabled: false
      migrate-at-start: true
      baseline-on-migrate: true
    stg:
      schemas: stg
      locations: 'classpath:db/migration/stg'
      create-schemas: false
      clean-at-start: true
      clean-disabled: false
      migrate-at-start: true
      baseline-on-migrate: true
    #dwh:
    #  schemas: dwh
    #  locations: 'classpath:db/migration/dwh'
    #  create-schemas: false
    #  clean-at-start: true
    #  clean-disabled: false
    #  migrate-at-start: true
    #  baseline-on-migrate: true
    #dm_companies:
    #  schemas: dm_companies
    #  locations: 'classpath:db/migration/dm_companies'
    #  create-schemas: false
    #  clean-at-start: true
    #  clean-disabled: false
    #  migrate-at-start: true
    #  baseline-on-migrate: true

logging:
  level:
    'org.springframework': INFO
    #'org.springframework': INFO
    'fr.dademo.bi': DEBUG
    'fr.dademo.bi.companies.tools': TRACE
    'org.flywaydb.core': DEBUG
    'org.jooq.Constants': WARN
    #'okhttp3': DEBUG
    'okhttp3': INFO

datasources:
  jdbc:
    stg:
      enabled: false
      url: jdbc:postgresql://localhost:5432/bi
      username: bi_rw
      password: bi_rw
  mongodb:
    stg:
      enabled: true
      connection-string: mongodb://root:root@localhost:27017/stg
      database: stg

batch:
  jobs:
    naf:
      enabled: true
      batch-size: 1000
      writer-type: MONGODB
      max-threads: null
    company:
      enabled: true
      batch-size: 100000
      writer-type: MONGODB
      max-threads: null
    company-history:
      enabled: false
      batch-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    company-inheritance:
      enabled: false
      batch-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    company-legal:
      enabled: false
      batch-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    company-legal-history:
      enabled: false
      batch-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    association:
      enabled: false
      batch-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    association-waldec:
      enabled: false
      batch-size: 100000
      writer-type: NO_ACTION
      max-threads: null
