spring:
  batch:
    initialize-schema: always

management:
  metrics:
    enable:
      spring.integration: false

flyway:
  migrations:
    batch:
      enabled: true
      schemas: public
    stg:
      enabled: true
      schemas: stg

logging:
  level:
    #'org.springframework': DEBUG
    'org.springframework': INFO
    'fr.dademo.bi': DEBUG
    'fr.dademo.bi.companies.tools': TRACE
    'org.flywaydb.core': DEBUG
    'org.jooq.Constants': WARN
    #'okhttp3': DEBUG
    'okhttp3': INFO

datasources:
  jdbc:
    batch:
      enabled: true
      driver-class-name: org.sqlite.JDBC
      url: "jdbc:sqlite:jobs.sqlite"
      minimum-idle: 1
      maximum-pool-size: 1
    stg:
      enabled: false
      url: jdbc:postgresql://localhost:5432/bi
      username: bi_rw
      password: bi_rw
  mongodb:
    batch-repository:
      connection-string: mongodb://root:root@localhost:27017/batch
      database: batch
    stg:
      enabled: true
      connection-string: mongodb://root:root@localhost:27017/stg
      database: stg

batch:
  repository:
    enabled: true
    table-prefix: BATCH_
  jobs:
    naf:
      enabled: true
      chunk-size: 1000
      writer-type: NO_ACTION
      #writer-type: MONGODB
      max-threads: null
    company:
      enabled: false
      chunk-size: 100000
      writer-type: NO_ACTION
      #writer-type: MONGODB
      max-threads: null
    company-history:
      enabled: false
      chunk-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    company-inheritance:
      enabled: false
      chunk-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    company-legal:
      enabled: false
      chunk-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    company-legal-history:
      enabled: false
      chunk-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    association:
      enabled: false
      chunk-size: 100000
      writer-type: NO_ACTION
      max-threads: null
    association-waldec:
      enabled: false
      chunk-size: 100000
      writer-type: NO_ACTION
      max-threads: null
