# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main
  - dev

jobs:
  - job: hello_world
    displayName: Hello World
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: CmdLine@2
        inputs:
          script: docker run --rm hello-world

  - job: unit_test_all
    displayName: Run all unit tests
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        clean: true
        lfs: true
        submodules: true
        persistCredentials: false
        enabled: true
      
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'test'
        enabled: true
    
