spring:
  application:
    name: Supervision task runner
  liquibase:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: supervisionConsumer
    stream:
      default-binder: rabbit
      rabbit:
        bindings:
          supervision:
            consumer:
              autoBindDlq: false
              bindingRoutingKey: '#'
              bindQueue: true
              declareDlx: false
              declareExchange: true
              exchangeType: direct
              exchangeDurable: true
              exchangeAutoDelete: false
              exclusive: false
              queueNameGroupOnly: true
              republishToDlq: false
      bindings:
        supervision:
          destination: supervision
          group: supervision
          consumer:
            maxAttempts: 1

persistence:
  datasource:
    url: jdbc:postgresql://localhost:5432/supervision
    username: postgres
    password: postgres
    schema: supervision

module:
  datasource:
    url: jdbc:postgresql://localhost:5432/bi
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    #root: DEBUG
    fr.dademo: DEBUG
