spring:
  application:
    name: Supervision task runner
  liquibase:
    enabled: false

task:
  datasource:
    url: jdbc:postgresql://localhost:5432/supervision
    username: postgres
    password: postgres
    schema: supervision

module:
  datasource:
    url: jdbc:postgresql://localhost:5432/bi
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    #root: DEBUG
    fr.dademo: DEBUG
