spring:
  application:
    name: Supervision task runner
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/bi
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      default-schema: supervision

logging:
  level:
    root: INFO
    #root: DEBUG
    fr.dademo: DEBUG

management:
  endpoints:
    enabled-by-default: true

springdoc:
  swagger-ui:
    path: /swagger
    #layout: StandaloneLayout
    layout: BaseLayout
