spring:
  application:
    name: Supervision query service
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/supervision
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    properties:
      'hibernate.default_schema': supervision

logging:
  level:
    root: INFO
    #root: DEBUG
    fr.dademo: DEBUG

management:
  endpoints:
    enabled-by-default: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    configUrl: /openapi/swagger-config
    layout: StandaloneLayout
    urlsPrimaryName: localhost
    urls:
      - name: localhost
        url: /openapi
    #layout: BaseLayout
  show-actuator: false
  model-and-view-allowed: true
  pre-loading-enabled: true
  api-docs:
    path: /openapi
    groups:
      enabled: false
