spring:
  application:
    name: Supervision task runner
  liquibase:
    enabled: false

persistence:
  cache-enabled: false
  batch-size: 100
  minimum-idle: 1
  maximum-pool-size: 1
  datasource:
    url: jdbc:postgresql://localhost:5432/supervision
    username: postgres
    password: postgres
    schema: supervision

task:
  datasource:
    url: jdbc:postgresql://localhost:5432/supervision
    username: postgres
    password: postgres
    schema: supervision

module:
  datasource:
    url: jdbc:postgresql://localhost:5432/bi
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    #root: DEBUG
    fr.dademo: DEBUG
